name: introduction_screen
description: Introduction/Onboarding package for flutter app with some customizations possibilities
version: 3.1.11
homepage: https://github.com/pyozer/introduction_screen

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.17.2
  dots_indicator: ^3.0.0
  flutter_keyboard_visibility: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
